name: seating_planner
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.2.2
  printing: ^5.14.2
  pdf: ^3.11.3
  reorderable_grid_view: ^2.2.8
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  package_info_plus: ^8.1.1
  path_provider: ^2.1.5
  path: ^1.9.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/Sitzordnungs-Gen.-App-Icon.png"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "assets/images/Sitzordnungs-Gen.-App-Icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/Sitzordnungs-Gen.-App-Icon.png"

flutter:
  uses-material-design: true